[pytest]
addopts = --alluredir=allure-results -v -s
testpaths = tests
pythonpath = .

markers =
    get: GET-запросы
    post: POST-запросы
    put: PUT-запросы
    delete: DELETE-запросы
    api: API тесты
    smoke: Критически важные тесты
    positive: Позитивные тесты
    negative: Негативные тесты